spring:
  redis:
    database: 0
    host: 59.110.160.100
    port: 6379
    password: leson24s00x0024ff18s7605fd58333leonqwertgsyuimnbvcz
    timeout: 36000 #超时时间
    jedis:
      pool:
        max-active: 200 #最大连接数
        max-idle: 100 #最大空闲连接 默认8
        max-wait: 100  #默认-1 最大连接阻塞等待时间
        min-idle: 0 #最小空闲连接

